import '@coinbase/onchainkit/styles.css';
import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import React from 'react';

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description: 'Generated by `create-onchain`, a Next.js template for OnchainKit',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Adobe Fonts Roc Grotesk */}
        <link rel="stylesheet" href="https://use.typekit.net/adq1bgp.css" />
        {/* Farcaster Mini App Embed Meta Tag (correct format) */}
        <meta
          name="fc:frame"
          content='{"version":"1","imageUrl":"https://beings-club.vercel.app/splash.png","button":{"title":"Open Beings Club","action":{"type":"launch_frame","url":"https://beings-club.vercel.app","name":"Beings Club","splashImageUrl":"https://beings-club.vercel.app/splash.png","splashBackgroundColor":"#000000"}}}'
        />
      </head>
      <body className="bg-background dark">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
