import '@coinbase/onchainkit/styles.css';
import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import React from 'react';

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description: 'Generated by `create-onchain`, a Next.js template for OnchainKit',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Adobe Fonts Roc Grotesk */}
        <link rel="stylesheet" href="https://use.typekit.net/adq1bgp.css" />
        {/* Farcaster Mini App Embed Meta Tags */}
        <meta property="fc:frame" content="vNext" />
        <meta property="fc:frame:image" content="https://beings-club.vercel.app/splash.png" />
        <meta property="fc:frame:button:1" content="Open Beings Club" />
        <meta property="og:title" content="Beings Club" />
        <meta property="og:description" content="A gathering place for beings" />
        <meta property="og:image" content="https://beings-club.vercel.app/splash.png" />
      </head>
      <body className="bg-background dark">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
